config/routes.rb
Rails.application.routes.draw do
  
  
  resources :positives, except: [:edit, :update, :destroy] do
    resources :pos_comments, except: [:edit, :update, :destroy]
  end
  resources :negatives, except: [:destroy] do
    resources :neg_comments, except: [:edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pos_comment.rb
class PosComment < ApplicationRecord
  validates :body, presence: true
  validates_inclusion_of :positive_reaction, in: [true, false]
end

app/controllers/pos_comments_controller.rb
class PosCommentsController < ApplicationController
  before_action :set_pos_comment, only: [:show, :edit, :update, :destroy]

  # GET /pos_comments
  # GET /pos_comments.json
  def index
    @pos_comments = PosComment.all
  end

  # GET /pos_comments/1
  # GET /pos_comments/1.json
  def show
  end

  # GET /pos_comments/new
  def new
    @pos_comment = PosComment.new
  end

  # GET /pos_comments/1/edit
  def edit
  end

  # POST /pos_comments
  # POST /pos_comments.json
  def create
    @pos_comment = PosComment.new(pos_comment_params)

    respond_to do |format|
      if @pos_comment.save
        format.html { redirect_to @pos_comment, notice: 'Pos comment was successfully created.' }
        format.json { render :show, status: :created, location: @pos_comment }
      else
        format.html { render :new }
        format.json { render json: @pos_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pos_comments/1
  # PATCH/PUT /pos_comments/1.json
  def update
    respond_to do |format|
      if @pos_comment.update(pos_comment_params)
        format.html { redirect_to @pos_comment, notice: 'Pos comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @pos_comment }
      else
        format.html { render :edit }
        format.json { render json: @pos_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pos_comments/1
  # DELETE /pos_comments/1.json
  def destroy
    @pos_comment.destroy
    respond_to do |format|
      format.html { redirect_to pos_comments_url, notice: 'Pos comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pos_comment
      @pos_comment = PosComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pos_comment_params
      params.require(:pos_comment).permit(:body, :positive_reaction)
    end
end

app/helpers/pos_comments_helper.rb
module PosCommentsHelper
end

app/views/pos_comments/_form.html.haml
= form_for @pos_comment do |f|
  - if @pos_comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pos_comment.errors.count, "error")} prohibited this pos_comment from being saved:"
      %ul
        - @pos_comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :positive_reaction
    = f.check_box :positive_reaction
  .actions
    = f.submit 'Save'

app/views/pos_comments/edit.html.haml
%h1 Editing pos_comment

= render 'form'

= link_to 'Show', @pos_comment
\|
= link_to 'Back', pos_comments_path

app/views/pos_comments/index.html.haml
%h1 Listing pos_comments

%table
  %thead
    %tr
      %th Body
      %th Positive reaction
      %th
      %th
      %th

  %tbody
    - @pos_comments.each do |pos_comment|
      %tr
        %td= pos_comment.body
        %td= pos_comment.positive_reaction
        %td= link_to 'Show', pos_comment
        %td= link_to 'Edit', edit_pos_comment_path(pos_comment)
        %td= link_to 'Destroy', pos_comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Pos comment', new_pos_comment_path

app/views/pos_comments/new.html.haml
%h1 New pos_comment

= render 'form'

= link_to 'Back', pos_comments_path

app/views/pos_comments/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @pos_comment.body
%p
  %b Positive reaction:
  = @pos_comment.positive_reaction

= link_to 'Edit', edit_pos_comment_path(@pos_comment)
\|
= link_to 'Back', pos_comments_path