config/routes.rb
Rails.application.routes.draw do
  
  
  resources :positives, except: [:edit, :update, :destroy] do
    resources :pos_comments, except: [:edit, :update, :destroy]
  end
  resources :negatives, except: [:destroy] do
    resources :neg_comments, except: [:edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/positive.rb
class Positive < ApplicationRecord

  validates :title, presence: true
  validates :description, presence: true
  validates :when, presence: true

  has_many :pos_comments

end

app/controllers/positives_controller.rb
class PositivesController < ApplicationController
  before_action :set_positive, only: [:show, :edit, :update, :destroy]

  # GET /positives
  # GET /positives.json
  def index
    @positives = Positive.all
  end

  # GET /positives/1
  # GET /positives/1.json
  def show
  end

  # GET /positives/new
  def new
    @positive = Positive.new
  end

  # GET /positives/1/edit
  def edit
  end

  # POST /positives
  # POST /positives.json
  def create
    @positive = Positive.new(positive_params)

    respond_to do |format|
      if @positive.save
        format.html { redirect_to @positive, notice: 'Positive was successfully created.' }
        format.json { render :show, status: :created, location: @positive }
      else
        format.html { render :new }
        format.json { render json: @positive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positives/1
  # PATCH/PUT /positives/1.json
  def update
    respond_to do |format|
      if @positive.update(positive_params)
        format.html { redirect_to @positive, notice: 'Positive was successfully updated.' }
        format.json { render :show, status: :ok, location: @positive }
      else
        format.html { render :edit }
        format.json { render json: @positive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positives/1
  # DELETE /positives/1.json
  def destroy
    @positive.destroy
    respond_to do |format|
      format.html { redirect_to positives_url, notice: 'Positive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_positive
      @positive = Positive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def positive_params
      params.require(:positive).permit(:title, :description, :when)
    end
end

app/helpers/positives_helper.rb
module PositivesHelper
end

app/views/positives/_form.html.haml
= form_for(positive) do |f|
  - if positive.errors.any?
    #error_explanation
      %h2
        = pluralize(positive.errors.count, "error")
        prohibited this positive from being saved:
      %ul
        - positive.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :when
    = f.datetime_select :when
  .actions
    = f.submit

app/views/positives/edit.html.haml
%h1 Editing Positive
= render 'form', positive: @positive
= link_to 'Show', @positive
|
= link_to 'Back', positives_path

app/views/positives/index.html.haml
%p#notice= notice
%h1 Positives
%table
  %thead
    %tr
      %th Title
      %th Description
      %th When
      %th{:colspan => "3"}
  %tbody
    - @positives.each do |positive|
      %tr
        %td= positive.title
        %td= positive.description
        %td= positive.when
        %td= link_to 'Show', positive
        %td= link_to 'Edit', edit_positive_path(positive)
        %td= link_to 'Destroy', positive, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Positive', new_positive_path

app/views/positives/new.html.haml
%h1 New Positive
= render 'form', positive: @positive
= link_to 'Back', positives_path

app/views/positives/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @positive.title
%p
  %strong Description:
  = @positive.description
%p
  %strong When:
  = @positive.when
= link_to 'Edit', edit_positive_path(@positive)
|
= link_to 'Back', positives_path