config/routes.rb
Rails.application.routes.draw do
  
  
  resources :positives, except: [:edit, :update, :destroy] do
    resources :pos_comments, except: [:edit, :update, :destroy]
  end
  resources :negatives, except: [:destroy] do
    resources :neg_comments, except: [:edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/neg_comment.rb
class NegComment < ApplicationRecord
  validates :body, presence: true
  validates_inclusion_of :positive_reaction, in: [true, false]
end

app/controllers/neg_comments_controller.rb
class NegCommentsController < ApplicationController
  before_action :set_neg_comment, only: [:show, :edit, :update, :destroy]

  # GET /neg_comments
  # GET /neg_comments.json
  def index
    @neg_comments = NegComment.all
  end

  # GET /neg_comments/1
  # GET /neg_comments/1.json
  def show
  end

  # GET /neg_comments/new
  def new
    @neg_comment = NegComment.new
  end

  # GET /neg_comments/1/edit
  def edit
  end

  # POST /neg_comments
  # POST /neg_comments.json
  def create
    @neg_comment = NegComment.new(neg_comment_params)

    respond_to do |format|
      if @neg_comment.save
        format.html { redirect_to @neg_comment, notice: 'Neg comment was successfully created.' }
        format.json { render :show, status: :created, location: @neg_comment }
      else
        format.html { render :new }
        format.json { render json: @neg_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neg_comments/1
  # PATCH/PUT /neg_comments/1.json
  def update
    respond_to do |format|
      if @neg_comment.update(neg_comment_params)
        format.html { redirect_to @neg_comment, notice: 'Neg comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @neg_comment }
      else
        format.html { render :edit }
        format.json { render json: @neg_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neg_comments/1
  # DELETE /neg_comments/1.json
  def destroy
    @neg_comment.destroy
    respond_to do |format|
      format.html { redirect_to neg_comments_url, notice: 'Neg comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neg_comment
      @neg_comment = NegComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neg_comment_params
      params.require(:neg_comment).permit(:body, :positive_reaction)
    end
end

app/helpers/neg_comments_helper.rb
module NegCommentsHelper
end

app/views/neg_comments/_form.html.haml
= form_for @neg_comment do |f|
  - if @neg_comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@neg_comment.errors.count, "error")} prohibited this neg_comment from being saved:"
      %ul
        - @neg_comment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :positive_reaction
    = f.check_box :positive_reaction
  .actions
    = f.submit 'Save'

app/views/neg_comments/edit.html.haml
%h1 Editing neg_comment

= render 'form'

= link_to 'Show', @neg_comment
\|
= link_to 'Back', neg_comments_path

app/views/neg_comments/index.html.haml
%h1 Listing neg_comments

%table
  %thead
    %tr
      %th Body
      %th Positive reaction
      %th
      %th
      %th

  %tbody
    - @neg_comments.each do |neg_comment|
      %tr
        %td= neg_comment.body
        %td= neg_comment.positive_reaction
        %td= link_to 'Show', neg_comment
        %td= link_to 'Edit', edit_neg_comment_path(neg_comment)
        %td= link_to 'Destroy', neg_comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Neg comment', new_neg_comment_path

app/views/neg_comments/new.html.haml
%h1 New neg_comment

= render 'form'

= link_to 'Back', neg_comments_path

app/views/neg_comments/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @neg_comment.body
%p
  %b Positive reaction:
  = @neg_comment.positive_reaction

= link_to 'Edit', edit_neg_comment_path(@neg_comment)
\|
= link_to 'Back', neg_comments_path