config/routes.rb
Rails.application.routes.draw do
  
  
  resources :positives, except: [:edit, :update, :destroy] do
    resources :pos_comments, except: [:edit, :update, :destroy]
  end
  resources :negatives, except: [:destroy] do
    resources :neg_comments, except: [:edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/negative.rb
class Negative < ApplicationRecord

  validates :title, presence: true
  validates :description, presence: true
  validates :when, presence: true
  
  has_many :neg_comments
  
end

app/controllers/negatives_controller.rb
class NegativesController < ApplicationController
  before_action :set_negative, only: [:show, :edit, :update, :destroy]

  # GET /negatives
  # GET /negatives.json
  def index
    @negatives = Negative.all
  end

  # GET /negatives/1
  # GET /negatives/1.json
  def show
  end

  # GET /negatives/new
  def new
    @negative = Negative.new
  end

  # GET /negatives/1/edit
  def edit
  end

  # POST /negatives
  # POST /negatives.json
  def create
    @negative = Negative.new(negative_params)

    respond_to do |format|
      if @negative.save
        format.html { redirect_to @negative, notice: 'Negative was successfully created.' }
        format.json { render :show, status: :created, location: @negative }
      else
        format.html { render :new }
        format.json { render json: @negative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /negatives/1
  # PATCH/PUT /negatives/1.json
  def update
    respond_to do |format|
      if @negative.update(negative_params)
        format.html { redirect_to @negative, notice: 'Negative was successfully updated.' }
        format.json { render :show, status: :ok, location: @negative }
      else
        format.html { render :edit }
        format.json { render json: @negative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /negatives/1
  # DELETE /negatives/1.json
  def destroy
    @negative.destroy
    respond_to do |format|
      format.html { redirect_to negatives_url, notice: 'Negative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_negative
      @negative = Negative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def negative_params
      params.require(:negative).permit(:title, :description, :when)
    end
end

app/helpers/negatives_helper.rb
module NegativesHelper
end

app/views/negatives/_form.html.haml
= form_for(negative) do |f|
  - if negative.errors.any?
    #error_explanation
      %h2
        = pluralize(negative.errors.count, "error")
        prohibited this negative from being saved:
      %ul
        - negative.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :when
    = f.datetime_select :when
  .actions
    = f.submit

app/views/negatives/edit.html.haml
%h1 Editing Negative
= render 'form', negative: @negative
= link_to 'Show', @negative
|
= link_to 'Back', negatives_path

app/views/negatives/index.html.haml
%p#notice= notice
%h1 Negatives
%table
  %thead
    %tr
      %th Title
      %th Description
      %th When
      %th{:colspan => "3"}
  %tbody
    - @negatives.each do |negative|
      %tr
        %td= negative.title
        %td= negative.description
        %td= negative.when
        %td= link_to 'Show', negative
        %td= link_to 'Edit', edit_negative_path(negative)
        %td= link_to 'Destroy', negative, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Negative', new_negative_path

app/views/negatives/new.html.haml
%h1 New Negative
= render 'form', negative: @negative
= link_to 'Back', negatives_path

app/views/negatives/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @negative.title
%p
  %strong Description:
  = @negative.description
%p
  %strong When:
  = @negative.when
= link_to 'Edit', edit_negative_path(@negative)
|
= link_to 'Back', negatives_path